management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  jpa:
    show-sql: true
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
            jdbc:
                lob:
                  non_contextual_creation: =true


  datasource:
    url: jdbc:mysql://localhost:3306/payment_app
    username: root
    password: root


app:
  user:
    password: 1234
    email: vet@gmail.com

info:
  app:
    name: Spring boot Payment App
    description: This is my first spring boot application
    version: 0.0.1
